properties:
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: string
    name: repository
    value: ${REPOSITORY}
triggers:
  - type: git
    branch: master
    events:
      pull_request: true
    name: Git Trigger - PR
    eventListener: ${event-listener-name}
    properties:
      - type: secure
        name: TF_VAR_ibmcloud_api_key
        value: ${API_KEY}
      - type: text
        name: tf-dir
        value: /
inputs:
  - type: git
    path: .tekton
    branch: main
    service: ${toolchain-terraform-cra}
  - type: git
    path: tasks
    branch: main
    service: ${toolchain-terraform-cra}
  - type: git
    path: cra
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: git
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: toolchain
    branch: master
    service: ${tekton-catalog}